### ISSUE TITLE
未定义函数或变量 'im2gray'。

### ISSUE THREAD

**Issue by yuan1311467** [ExplodingONC/Local_Dimming_test#2]
不好意思，还有问题嘻嘻。这个函数也没有

**Comment by ExplodingONC** [comment]
https://www.mathworks.com/help/matlab/ref/im2gray.html
im2gray是MATLAB2020b引入的函数，自己去升级版本即可。或者在确认只输入rgb图像时也可以考虑用rgb2gray代替。

**Comment by yuan1311467** [comment]
谢谢啦
